WIDTH = 1100
HEIGHT = 763

WIDTH_INTERACTIVE_WINDOW = 337

PROGRESS_WIDTH = 800

START_BG = "#D8BFD8"
PRESENT_BG = "black"
RADIO_BG = "#e7d5e7"

SYSTEM_FG = "#DC143C"
SYSTEM_HOVER = "#8B0000"

FIELD_COLOR = "#c7f4bd"

PATH_LOGO_START = "images/LogoStart.png"
PATH_LOGO_GAME = "images/logo.png"

RADIO_BUTTON_TEXT_2 = "2 Players"
RADIO_BUTTON_TEXT_3 = "3 Players"
RADIO_BUTTON_TEXT_4 = "4 Players"
RADIO_BUTTON_TEXT_5 = "5 Players"
RADIO_BUTTON_TEXT_6 = "6 Players"

START_BUTTON_TEXT = "Start"
